application: auriga-squad
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /update
  script: update.py
  login: admin

- url: /upload
  script: upload.py

- url: /find
  script: find.py

- url: /get/.*
  script: download.py

- url: /rate/.*
  script: rate.py

- url: /
  static_dir: static/
